### ISSUE TITLE
Include file missing from zip file download on wordpress.org repository

### ISSUE THREAD

**Issue by forkless** [jeffreyvr/easy-liveblogs#2]
The zip file hosted for version 1.4 is missing the elb-social-logos.php include file. Updating manually or from within WordPress at the moment will break the plugin/site and generate a "critical error" page and the site can only be accessed in administrative mode from that point on.

**Comment by jeffreyvr** [comment]
Thanks for reporting @forkless. Somehow the file was missing in the trunk, but was added in the tagged version. I have now added the file to prevent further issues.

**Comment by forkless** [comment]
Thanks!
