### ISSUE TITLE
New post suffixes surplus character to post title

### ISSUE THREAD

**Issue by forkless** [jeffreyvr/easy-liveblogs#3]
A couple of months ago we noticed that on creating a new post that the Liveblog title suffixes an ￼ character.

WordPress: 5.9.3
Easy Liveblogs: 1.7.0
PHP: 7.4.28 (Supports 64bit values)
Apache: Apache/2.4.25 (Debian)
MySQL: 10.1.48-MariaDB-0+deb9u2

**Comment by jeffreyvr** [comment]
Can you provide me with some more info @forkless. Maybe a screenshot? Can't seem to find the issue your describing.

**Comment by forkless** [comment]
You can close this question. After doing some checks with the people creating the content this isn't an issue with this plugin. 

(ps. It is related to Gutenberg not filtering excess HTML in the title field when HTML is being pasted)
